import type { CaseSpec } from '../../contracts/src/index.ts';
export const CASES: CaseSpec[] = [
  {
    id: 'C01',
    title: '合法申请保存为草稿',
    category: '正常流程',
    ruleIds: ['R01', 'R02'],
    steps: ['申请人登录', '填写标题与金额 100', '保存申请', '查询持久化记录'],
    assertionIds: ['record.status', 'record.amount'],
    expected: '生成 1 条草稿，金额为 100',
  },
  {
    id: 'C02',
    title: '提交后由另一人审批通过',
    category: '正常流程',
    ruleIds: ['R03', 'R04'],
    steps: ['创建并提交申请', '切换审批人', '点击通过', '核对状态、审批人和审计事件'],
    assertionIds: ['record.status', 'record.reviewer', 'audit.approve'],
    expected: '状态 APPROVED，审批人为 reviewer，存在通过事件',
  },
  {
    id: 'C03',
    title: '审批人驳回申请',
    category: '正常流程',
    ruleIds: ['R03', 'R05'],
    steps: ['创建并提交申请', '切换审批人', '点击驳回', '核对持久化状态'],
    assertionIds: ['record.status', 'record.reviewer'],
    expected: '状态 REJECTED，记录审批人',
  },
  {
    id: 'C04',
    title: '标题为空时拒绝保存',
    category: '表单边界',
    ruleIds: ['R01'],
    steps: ['标题留空', '填写合法金额', '保存', '核对错误提示和记录数量'],
    assertionIds: ['record.count', 'ui.validation'],
    expected: '显示标题校验错误，不产生记录',
  },
  {
    id: 'C05',
    title: '标题超过 200 字时拒绝保存',
    category: '表单边界',
    ruleIds: ['R01'],
    steps: ['填写 201 字标题', '保存', '核对校验与记录数量'],
    assertionIds: ['record.count', 'ui.validation'],
    expected: '拒绝超长标题，不产生记录',
  },
  {
    id: 'C06',
    title: '金额为零时拒绝保存',
    category: '金额边界',
    ruleIds: ['R02'],
    steps: ['填写金额 0', '保存', '核对校验与记录数量'],
    assertionIds: ['record.count', 'ui.validation'],
    expected: '金额必须大于 0，不产生记录',
  },
  {
    id: 'C07',
    title: '金额为负数时拒绝保存',
    category: '金额边界',
    ruleIds: ['R02'],
    steps: ['填写金额 -1', '保存', '核对校验与记录数量'],
    assertionIds: ['record.count', 'ui.validation'],
    expected: '拒绝负金额，不产生记录',
  },
  {
    id: 'C08',
    title: '金额超过上限时拒绝保存',
    category: '金额边界',
    ruleIds: ['R02'],
    steps: ['填写金额 1000001', '保存', '核对校验与记录数量'],
    assertionIds: ['record.count', 'ui.validation'],
    expected: '金额不得超过 1000000，不产生记录',
  },
  {
    id: 'C09',
    title: '普通申请人不能审批他人申请',
    category: '角色权限',
    ruleIds: ['R04', 'R06'],
    steps: ['准备他人待审批申请', '普通申请人打开审批页', '尝试审批', '核对请求被拒绝且状态未变'],
    assertionIds: ['record.status', 'audit.noApprove', 'ui.denied'],
    expected: '拒绝无审批角色用户，状态仍 PENDING',
  },
  {
    id: 'C10',
    title: '审批角色也不能审批自己的申请',
    category: '角色权限',
    ruleIds: ['R04', 'R07'],
    steps: ['以审批角色创建自己的申请', '提交后尝试自审批', '核对拒绝提示、状态与审计'],
    assertionIds: ['record.status', 'audit.noApprove', 'ui.denied'],
    expected: '自审批被拒绝，状态仍 PENDING，无通过事件',
  },
  {
    id: 'C11',
    title: '重复提交只产生一次状态变更',
    category: '幂等性',
    ruleIds: ['R03', 'R08'],
    steps: ['创建申请', '连续两次点击提交', '查询提交计数和审计'],
    assertionIds: ['record.status', 'record.submitCount', 'audit.submitCount'],
    expected: '状态 PENDING，submitCount 和 submit 审计均为 1',
  },
  {
    id: 'C12',
    title: '跨租户访问不能读取或审批',
    category: '租户隔离',
    ruleIds: ['R06', 'R09'],
    steps: ['准备租户 A 申请', '切换租户 B 用户访问', '尝试读取', '核对拒绝提示与原记录'],
    assertionIds: ['record.status', 'ui.denied', 'audit.noApprove'],
    expected: '跨租户拒绝访问，原记录状态未变',
  },
].map((c) => ({
  ...c,
  ruleIds: [
    ...new Set([
      ...c.ruleIds,
      'R10',
      ...(['C01'].includes(c.id) ? ['R03'] : []),
      ...(['C03'].includes(c.id) ? ['R04'] : []),
      ...(['C10'].includes(c.id) ? ['R06'] : []),
    ]),
  ],
  assertionIds: ['C04', 'C05', 'C06', 'C07', 'C08'].includes(c.id)
    ? c.assertionIds
    : [
        ...new Set([
          'record.count',
          ...c.assertionIds.filter((id) => id !== 'audit.approve'),
          ...(['C02', 'C03'].includes(c.id) ? ['audit.review'] : []),
          ...(c.id === 'C12' ? ['ui.noForeignRecord'] : []),
        ]),
      ],
}));
export const RULES = [
  { id: 'R01', title: '申请标题', text: '标题去除首尾空格后长度为 1-200 个字符。' },
  { id: 'R02', title: '金额范围', text: '金额须为 1-1000000 的整数；零、负数与超限数值均拒绝。' },
  { id: 'R03', title: '状态转换', text: '草稿可提交为 PENDING；已提交申请重复提交不重复记账。' },
  { id: 'R04', title: '审批条件', text: '审批人须拥有 reviewer 角色；仅 PENDING 可审批，记录实际审批人。' },
  { id: 'R05', title: '驳回条件', text: '合法审批人可将 PENDING 改为 REJECTED 并记录审计。' },
  { id: 'R06', title: '对象授权', text: '操作前校验用户角色、租户和业务对象；请求失败不产生业务变更。' },
  { id: 'R07', title: '禁止自审批', text: '申请人不能审批自己的申请，即使其同时具备 reviewer 角色。' },
  { id: 'R08', title: '提交幂等', text: '同一申请提交只发生一次状态转换及一次 submit 审计。' },
  { id: 'R09', title: '租户隔离', text: '租户之间不可读取或修改对方申请。' },
  { id: 'R10', title: '证据与清理', text: '不能仅凭成功提示判定通过；查询持久化结果并按 run_id 清理数据。' },
].map((r) => ({
  ...r,
  source: 'sample-approval-spec@1.0',
  owner: '样例业务维护者',
  status: 'SAMPLE_APPROVED',
}));
export const toolCatalog = [
  {
    id: 'midscene.ui',
    name: 'Midscene 通用 UI 执行',
    type: 'SDK',
    version: '1.0.0',
    effect: 'test-write',
    description: '用自然语言执行操作、输入、等待和视觉断言；页面预期由 Midscene 核验，保留截图与报告。',
  },
  {
    id: 'knowledge.search',
    name: '知识查询',
    type: 'SDK',
    version: '1.0.0',
    effect: 'read',
    description: '在已锁定且授权的知识快照中查找规则与流程。',
  },
  {
    id: 'browser.run_case',
    name: '浏览器测试',
    type: 'SDK',
    version: '1.0.0',
    effect: 'test-write',
    description: '执行已注册用例；独立浏览器会话，限定角色与数据命名空间。',
  },
  {
    id: 'business.query',
    name: '业务状态查询',
    type: 'HTTP',
    version: '1.0.0',
    effect: 'read',
    description: '向预配置业务端点查询本次运行的数据，供独立断言使用。',
  },
  {
    id: 'fixture.prepare',
    name: '测试数据准备',
    type: 'HTTP',
    version: '1.0.0',
    effect: 'test-write',
    description: '在本次 run 的隔离数据命名空间准备测试前置条件。',
  },
  {
    id: 'fixture.cleanup',
    name: '测试数据清理',
    type: 'HTTP',
    version: '1.0.0',
    effect: 'test-write',
    description: '仅清理当前任务命名空间的数据。',
  },
  {
    id: 'assertions.verify',
    name: '独立业务断言',
    type: 'SDK',
    version: '1.0.0',
    effect: 'read',
    description: '使用版本化规则核对实际业务状态，LLM 无权修改判定。',
  },
  {
    id: 'midscene.tap',
    name: '视觉单步操作',
    type: 'SDK',
    version: '1.0.0',
    effect: 'test-write',
    description: 'Midscene 执行当前页面的一次视觉点击；需要单独配置视觉模型。',
  },
];
export const ontology = {
  version: '1.0.0',
  entities: ['User', 'Role', 'Tenant', 'Application', 'State', 'Rule', 'Case', 'Assertion', 'Evidence'],
  relations: CASES.flatMap((c) => c.ruleIds.map((rule) => ({ from: c.id, type: 'verifies', to: rule }))),
};
